/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SistemaEducativo.Unid02.Class.View;

import SistemaEducativo.Unid02.Class.View.Tema04_TipoAbstractoDeDatos_Alumnos_view;
import SistemaEducativo.Unid02.Class.Tema04p2_TipoAbstractoDeDatos_ListaAlumno;
import SistemaEducativo.Unid02.Class.Tema04p1_TipoAbstractoDeDatos_NodoAlumno;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Tema04_TipoAbstractoDeDatos_BuscarAlumno_view extends javax.swing.JFrame {

    private static Tema04_TipoAbstractoDeDatos_BuscarAlumno_view instance;
    private final Tema04p2_TipoAbstractoDeDatos_ListaAlumno lista;
    private final DefaultTableModel modeloTabla;

    public static Tema04_TipoAbstractoDeDatos_BuscarAlumno_view getInstance() {
        if (instance == null) {
            instance = new Tema04_TipoAbstractoDeDatos_BuscarAlumno_view();
        }
        return instance;
    }

    /**
     * Creates new form NewJFrame
     */
    public Tema04_TipoAbstractoDeDatos_BuscarAlumno_view() {
        initComponents();
        lista = Tema04p2_TipoAbstractoDeDatos_ListaAlumno.getInstance();

        modeloTabla = new DefaultTableModel(
                new Object[][]{},
                new String[]{"CURSO", "1 TRIMESTRE", "2 TRIMESTRE", "3 TRIMESTRE", "PROMEDIO FINAL"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(modeloTabla);

        setTitle("Buscar Alumno");
        setSize(800, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        txtBuscar.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nombre1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        Apellido = new javax.swing.JLabel();
        Carrera = new javax.swing.JLabel();
        Nivel = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtGrado = new javax.swing.JTextField();
        txtNivel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtApellido = new javax.swing.JTextField();
        btnIrJFalumnos = new javax.swing.JButton();
        btnEliminar = new javax.swing.JToggleButton();

        Nombre.setText("Nombre");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BUSCAR ALUMNO");

        Nombre1.setText("Nombre");

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        Apellido.setText("Apellido");

        Carrera.setText("Grado");

        Nivel.setText("Nivel");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradoActionPerformed(evt);
            }
        });

        txtNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNivelActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CURSO", "1 TRIMESTRE", "2 TRIMESTRE", "3 TRIMESTRE", "PROMEDIO FINAL"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        btnIrJFalumnos.setText("AGREGAR ALUMNO");
        btnIrJFalumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrJFalumnosActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR ALUMNO");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnIrJFalumnos)
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(165, 165, 165)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Nombre1)
                                        .addComponent(Apellido)
                                        .addComponent(Carrera)
                                        .addComponent(Nivel))
                                    .addGap(39, 39, 39)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtGrado, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                            .addComponent(txtApellido)
                                            .addComponent(txtNivel))
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre1)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Carrera)
                    .addComponent(txtGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nivel)
                    .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIrJFalumnos)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        buscarPorNombreCompleto();
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGradoActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNivelActionPerformed

    private void btnIrJFalumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrJFalumnosActionPerformed
        Tema04_TipoAbstractoDeDatos_Alumnos_view.getInstance().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIrJFalumnosActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    try {
        if (txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty()) {
            mostrarError("Primero busque un alumno para eliminar");
            return;
        }
        
        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();
        String nivel = txtNivel.getText().trim(); // Obtenemos el nivel del alumno
        
        int confirmacion = JOptionPane.showConfirmDialog(
            this, 
            "¿Está seguro de eliminar a " + nombre + " " + apellido + "?", 
            "Confirmar eliminación", 
            JOptionPane.YES_NO_OPTION
        );
        
        if (confirmacion == JOptionPane.YES_OPTION) {

            boolean eliminado = lista.eliminarAlumno(nombre, apellido);
            
            if (eliminado) {
                mostrarInformacion("Alumno eliminado correctamente");
                limpiarCampos();

                if (Tema04_TipoAbstractoDeDatos_Alumnos_view.getInstance() != null) {
                    Tema04_TipoAbstractoDeDatos_Alumnos_view.getInstance().actualizarTablas(); 
                }
            } else {
                mostrarError("No se pudo eliminar el alumno");
            }
        }
    } catch (Exception e) {
        mostrarError("Error al eliminar: " + e.getMessage());
    }

    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> {
            Tema04_TipoAbstractoDeDatos_BuscarAlumno_view.getInstance().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel Carrera;
    private javax.swing.JLabel Nivel;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JToggleButton btnEliminar;
    private javax.swing.JButton btnIrJFalumnos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtGrado;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void buscarPorNombreCompleto() {
         String busqueda = txtBuscar.getText().trim();
    
    if (busqueda.isEmpty()) {
        mostrarError("Ingrese un nombre completo para buscar");
        return;
    }
    
    Tema04p1_TipoAbstractoDeDatos_NodoAlumno alumno = lista.buscarPorNombreCompleto(busqueda);
    
    if (alumno != null) {
        // Mostrar datos en los campos de texto
        txtNombre.setText(alumno.getNombre());
        txtApellido.setText(alumno.getApellido());
        txtGrado.setText(String.valueOf(alumno.getGrado()));
        txtNivel.setText(alumno.getNivel());
        
        // Actualizar tabla de notas
        actualizarTablaNotas(alumno.getNivel());
    } else {
        mostrarInformacion("No se encontró al alumno: " + busqueda);
        limpiarCampos();
    }
    }

    private void actualizarTablaNotas(String nivel) {
        modeloTabla.setRowCount(0);
        switch (nivel.toUpperCase()) {
            case "INICIAL":
                modeloTabla.addRow(new Object[]{"Comunicación", "15", "16", "17", "16"});
                modeloTabla.addRow(new Object[]{"Matemáticas", "14", "15", "16", "15"});
                break;
            case "PRIMARIA":
                modeloTabla.addRow(new Object[]{"Comunicación", "14", "15", "16", "15"});
                modeloTabla.addRow(new Object[]{"Matemáticas", "15", "14", "16", "15"});
                modeloTabla.addRow(new Object[]{"Ciencias", "16", "15", "17", "16"});
                break;
            case "SECUNDARIA":
                modeloTabla.addRow(new Object[]{"Comunicación", "13", "14", "15", "14"});
                modeloTabla.addRow(new Object[]{"Matemáticas", "14", "15", "13", "14"});
                modeloTabla.addRow(new Object[]{"Ciencias", "15", "14", "16", "15"});
                modeloTabla.addRow(new Object[]{"Historia", "14", "15", "16", "15"});
                break;
        }
    }

    private void limpiarCampos() {
        txtBuscar.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtGrado.setText("");
        txtNivel.setText("");
        modeloTabla.setRowCount(0);
        txtBuscar.requestFocus();
    }


    private void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Advertencia", JOptionPane.WARNING_MESSAGE);
    }

    private void mostrarInformacion(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Información", JOptionPane.INFORMATION_MESSAGE);
    }
}
