/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SistemaEducativo.Unid01.Class.View;

import SistemaEducativo.View.VentanaUnidad1;
import SistemaEducativo.Unid01.Class.Tema02_ArregloUnidimensional;
import javax.swing.JOptionPane;
/**
 *
 * @author Cesar
 */
public class Tema02_ArregloUnidimensional_view extends javax.swing.JFrame {
private Tema02_ArregloUnidimensional arreglo1 = new Tema02_ArregloUnidimensional();
private Tema02_ArregloUnidimensional arreglo2 = new Tema02_ArregloUnidimensional();
private int arregloActivo = 1;
 
private Tema02_ArregloUnidimensional getArregloActivo() {
    return arregloActivo == 1 ? arreglo1 : arreglo2;
    
}

private void actualizarVistaDeArreglos() {
    StringBuilder sb = new StringBuilder();

    sb.append("📦 Arreglo 1: ");
    if (arreglo1.getCapacidad() > 0) {
        sb.append(arreglo1.mostrar()).append("\n");
    } else {
        sb.append("No creado.\n");
    }

    sb.append("📦 Arreglo 2: ");
    if (arreglo2.getCapacidad() > 0) {
        sb.append(arreglo2.mostrar()).append("\n");
    } else {
        sb.append("No creado.\n");
    }

    txtAreaMuestra.setText(sb.toString());
}
    public Tema02_ArregloUnidimensional_view() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTamaño = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMuestra = new javax.swing.JTextArea();
        txtValores = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();
        btnComparar = new javax.swing.JButton();
        btnClonar = new javax.swing.JButton();
        btnFusionar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSeleccionarArreglo1 = new javax.swing.JButton();
        btnSeleccionarArreglo2 = new javax.swing.JButton();
        txtAreaSalida = new javax.swing.JTextField();
        txtCrear = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Arreglos Unidimensionales - Operaciones Avanzadas");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese el tamaño de un arreglo:");

        jLabel3.setText("Ingrese elementos del arreglo:");

        txtAreaMuestra.setEditable(false);
        txtAreaMuestra.setColumns(20);
        txtAreaMuestra.setRows(5);
        jScrollPane1.setViewportView(txtAreaMuestra);

        btnBorrar.setText("Borrar Arreglo");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnComparar.setText("Comparar");
        btnComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompararActionPerformed(evt);
            }
        });

        btnClonar.setText("Clonar");
        btnClonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClonarActionPerformed(evt);
            }
        });

        btnFusionar.setText("Fusionar");
        btnFusionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFusionarActionPerformed(evt);
            }
        });

        jLabel4.setText("Seleccionar Arreglo:");

        btnSeleccionarArreglo1.setText("Arreglo 1");
        btnSeleccionarArreglo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarArreglo1ActionPerformed(evt);
            }
        });

        btnSeleccionarArreglo2.setText("Arreglo 2");
        btnSeleccionarArreglo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarArreglo2ActionPerformed(evt);
            }
        });

        txtAreaSalida.setEditable(false);

        txtCrear.setText("Crear");
        txtCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCrearActionPerformed(evt);
            }
        });

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnComparar)
                                .addGap(18, 18, 18)
                                .addComponent(btnClonar)
                                .addGap(32, 32, 32)
                                .addComponent(btnFusionar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBorrar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSeleccionarArreglo1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSeleccionarArreglo2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtAreaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtValores, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnInsertar))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolver)
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnSeleccionarArreglo1)
                    .addComponent(btnSeleccionarArreglo2)
                    .addComponent(txtAreaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCrear))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnBorrar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComparar)
                    .addComponent(btnClonar)
                    .addComponent(btnFusionar))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarArreglo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarArreglo1ActionPerformed
        arregloActivo = 1;
        txtAreaSalida.setText("Trabajando con ARREGLO 1");
    }//GEN-LAST:event_btnSeleccionarArreglo1ActionPerformed

    private void btnSeleccionarArreglo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarArreglo2ActionPerformed
        arregloActivo = 2;
        txtAreaSalida.setText("Trabajando con ARREGLO 2");
    }//GEN-LAST:event_btnSeleccionarArreglo2ActionPerformed

    private void txtCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrearActionPerformed
        try {
            int tamaño = Integer.parseInt(txtTamaño.getText());

            if (tamaño <= 0) {
                JOptionPane.showMessageDialog(null, "El tamaño debe ser mayor que 0.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Tema02_ArregloUnidimensional arreglo = getArregloActivo();
            boolean creado = arreglo.crearArreglo(tamaño);

            if (creado) {
                JOptionPane.showMessageDialog(null, "Arreglo " + arregloActivo + " creado con tamaño " + tamaño + ".", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo crear el arreglo.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Ingrese un número válido para el tamaño.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtCrearActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        if (getArregloActivo().getCapacidad() == 0) {
            JOptionPane.showMessageDialog(null, "Primero debes crear el arreglo.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String texto = txtValores.getText().trim();

        if (texto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese al menos un valor.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int insertados = getArregloActivo().insertarVarios(texto);
        JOptionPane.showMessageDialog(null, insertados + " valores insertados en Arreglo " + arregloActivo + ".", "Insertado", JOptionPane.INFORMATION_MESSAGE);

      actualizarVistaDeArreglos();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        Tema02_ArregloUnidimensional arreglo = getArregloActivo();

        if (arreglo.getCapacidad() == 0) {
            JOptionPane.showMessageDialog(null, "El arreglo " + arregloActivo + " no ha sido creado.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(null, "¿Deseas borrar el arreglo " + arregloActivo + "?", "Confirmar", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            arreglo.borrarArreglo();
            JOptionPane.showMessageDialog(null, "Arreglo " + arregloActivo + " eliminado.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            actualizarVistaDeArreglos();
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnClonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClonarActionPerformed
        Tema02_ArregloUnidimensional arreglo = getArregloActivo();

        if (arreglo.getCapacidad() == 0 || arreglo.getElementos() == 0) {
            JOptionPane.showMessageDialog(null, "No hay datos para clonar en el arreglo " + arregloActivo + ".", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int[] clon = arreglo.clonar();

        JOptionPane.showMessageDialog(null, "Clon del arreglo " + arregloActivo + " creado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // Mostrar el arreglo clonado en el TextArea sin alterar los originales
        StringBuilder sb = new StringBuilder();
        actualizarVistaDeArreglos(); // primero mostrar los arreglos originales
        sb.append(txtAreaMuestra.getText()).append("\n");
        sb.append("🧬 Clon del arreglo ").append(arregloActivo).append(": ");
        for (int i = 0; i < clon.length; i++) {
            sb.append("[").append(i).append("]=").append(clon[i]).append("  ");
        }

        txtAreaMuestra.setText(sb.toString());
    }//GEN-LAST:event_btnClonarActionPerformed

    private void btnFusionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFusionarActionPerformed
        Tema02_ArregloUnidimensional a1 = arreglo1;
        Tema02_ArregloUnidimensional a2 = arreglo2;

        if (a1.getCapacidad() == 0 || a2.getCapacidad() == 0) {
            JOptionPane.showMessageDialog(null, "Ambos arreglos deben estar creados para fusionarlos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int[] fusion = a1.fusionar(a2.getArregloActual());

        JOptionPane.showMessageDialog(null, "Fusión completada: arreglo1 + arreglo2.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // Mostrar ambos arreglos y la fusión en el TextArea
        StringBuilder sb = new StringBuilder();
        actualizarVistaDeArreglos(); // primero muestra los arreglos originales
        sb.append(txtAreaMuestra.getText()).append("\n");

        sb.append("🔗 Fusión (arreglo1 + arreglo2): ");
        for (int i = 0; i < fusion.length; i++) {
            sb.append("[").append(i).append("]=").append(fusion[i]).append("  ");
        }

        txtAreaMuestra.setText(sb.toString());
    }//GEN-LAST:event_btnFusionarActionPerformed

    private void btnCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompararActionPerformed
        if (arreglo1.getCapacidad() == 0 || arreglo2.getCapacidad() == 0) {
            JOptionPane.showMessageDialog(null, "Ambos arreglos deben estar creados para comparar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean iguales = arreglo1.comparar(arreglo2.getArregloActual());

        // Mostrar resultado en un JOptionPane
        if (iguales) {
            JOptionPane.showMessageDialog(null, "Los arreglos son idénticos.", "Comparación", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Los arreglos son diferentes.", "Comparación", JOptionPane.INFORMATION_MESSAGE);
        }

        // Mostrar los dos arreglos y el resultado en el JTextArea
        StringBuilder sb = new StringBuilder();
        actualizarVistaDeArreglos(); // mostrar los dos arreglos
        sb.append(txtAreaMuestra.getText()).append("\n");
        sb.append("📌 Resultado de la comparación: ").append(iguales ? "Son iguales" : "Son diferentes");

        txtAreaMuestra.setText(sb.toString());
    }//GEN-LAST:event_btnCompararActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        VentanaUnidad1 unidad1 = new VentanaUnidad1();
        unidad1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tema02_ArregloUnidimensional_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tema02_ArregloUnidimensional_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tema02_ArregloUnidimensional_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tema02_ArregloUnidimensional_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tema02_ArregloUnidimensional_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnClonar;
    private javax.swing.JButton btnComparar;
    private javax.swing.JButton btnFusionar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnSeleccionarArreglo1;
    private javax.swing.JButton btnSeleccionarArreglo2;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaMuestra;
    private javax.swing.JTextField txtAreaSalida;
    private javax.swing.JButton txtCrear;
    private javax.swing.JTextField txtTamaño;
    private javax.swing.JTextField txtValores;
    // End of variables declaration//GEN-END:variables
}
